name: apple_tipkit
description: Flutter plugin (iOS 17+) - wrapper over Apple TipKit API via MethodChannel.
version: 0.1.1
homepage: https://pub.dev/packages/apple_tipkit
repository: https://github.com/Ellweb3/apple-tipkit
issue_tracker: https://github.com/Ellweb3/apple-tipkit/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppleTipkitPlugin

platforms:
  ios:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0


