name: apple_tipkit
description: Flutter-плагин (iOS 17+) — обёртка над Apple TipKit API через MethodChannel.
version: 0.1.0
homepage: https://pub.dev/packages/apple_tipkit
repository: https://github.com/your-org/apple_tipkit
issue_tracker: https://github.com/your-org/apple_tipkit/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppleTipkitPlugin

platforms:
  ios:
    # Документируем минимальную версию; фактически она будет принудительно задана в podspec
    minimum_os: 17.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0


